### ISSUE TITLE
Integrate

### ISSUE THREAD

**Issue by gsasouza** [gsasouza/hackathon-hu-backend#3]
pubmed
medline
lilax
Cochrane

**Comment by LucasReSilva** [comment]
Exemplo:
{"title": "MiR-374b Promotes Proliferation and Inhibits Apoptosis of Human GIST Cells by Inhibiting PTEN through Activation of the PI3K/Akt Pathway.", "url": "https://www.ncbi.nlm.nih.gov/pubmed/29902839", "similar": "https://www.ncbi.nlm.nih.gov/pubmed?linkname=pubmed_pubmed&from_uid=29902839", "num": "1", "details": "Mol Cells", "authors": ["Long ZW", " Wu JH", " Hong C", " Wang YN", " Zhou Y."], "PMID": "29902839", "type": "Free Article"}

**Comment by LucasReSilva** [comment]
Exemplo noticias
{"title": "Maratona tecnológica no HU já está em andamento", "abstract": "Durante as madrugadas da sexta e do sábado, e no decorrer do final de semana, maratonistas devem apresentar soluções para oito desafios.", "tag": "HACKATHON", "link": "http://www.ebserh.gov.br/web/hu-ufs/noticias/-/asset_publisher/GGPOGcvnnoeY/content/id/3201914/2018-06-maratona-tecnologica-no-hu-ja-esta-em-andamento", "time": "21h38", "date": "15/06/2018", "image": "http://www.ebserh.gov.br/documents/16756/3201821/HackathonAbertura.jpg/93c3ccb4-0355-4625-b294-8e50422f51c6?t=1529109500635&width=160"},
